//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference3
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservationDto", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceGestionBooks.Dto")]
    public partial class ReservationDto : object
    {
        
        private ServiceReference3.Book BookField;
        
        private int BookIdField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private int IdField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private ServiceReference3.User UserField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Book Book
        {
            get
            {
                return this.BookField;
            }
            set
            {
                this.BookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookId
        {
            get
            {
                return this.BookIdField;
            }
            set
            {
                this.BookIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceGestionBooks.DB")]
    public partial class Book : object
    {
        
        private string AuthorField;
        
        private System.Nullable<int> CopiesField;
        
        private int IdField;
        
        private ServiceReference3.Reservation[] ReservationsField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Copies
        {
            get
            {
                return this.CopiesField;
            }
            set
            {
                this.CopiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Reservation[] Reservations
        {
            get
            {
                return this.ReservationsField;
            }
            set
            {
                this.ReservationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceGestionBooks.DB")]
    public partial class User : object
    {
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        private string PasswordField;
        
        private ServiceReference3.Reservation[] ReservationsField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Reservation[] Reservations
        {
            get
            {
                return this.ReservationsField;
            }
            set
            {
                this.ReservationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceGestionBooks.DB")]
    public partial class Reservation : object
    {
        
        private ServiceReference3.Book BookField;
        
        private int BookIdField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private int IdField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private ServiceReference3.User UserField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Book Book
        {
            get
            {
                return this.BookField;
            }
            set
            {
                this.BookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookId
        {
            get
            {
                return this.BookIdField;
            }
            set
            {
                this.BookIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IReservationService")]
    public interface IReservationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetReservations", ReplyAction="http://tempuri.org/IReservationService/GetReservationsResponse")]
        ServiceReference3.ReservationDto[] GetReservations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetReservations", ReplyAction="http://tempuri.org/IReservationService/GetReservationsResponse")]
        System.Threading.Tasks.Task<ServiceReference3.ReservationDto[]> GetReservationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/DeleteReservation", ReplyAction="http://tempuri.org/IReservationService/DeleteReservationResponse")]
        void DeleteReservation(int ReservationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/DeleteReservation", ReplyAction="http://tempuri.org/IReservationService/DeleteReservationResponse")]
        System.Threading.Tasks.Task DeleteReservationAsync(int ReservationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/AddReservation", ReplyAction="http://tempuri.org/IReservationService/AddReservationResponse")]
        void AddReservation(ServiceReference3.ReservationDto reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/AddReservation", ReplyAction="http://tempuri.org/IReservationService/AddReservationResponse")]
        System.Threading.Tasks.Task AddReservationAsync(ServiceReference3.ReservationDto reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/UpdateReservation", ReplyAction="http://tempuri.org/IReservationService/UpdateReservationResponse")]
        void UpdateReservation(ServiceReference3.ReservationDto reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/UpdateReservation", ReplyAction="http://tempuri.org/IReservationService/UpdateReservationResponse")]
        System.Threading.Tasks.Task UpdateReservationAsync(ServiceReference3.ReservationDto reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetReservation", ReplyAction="http://tempuri.org/IReservationService/GetReservationResponse")]
        ServiceReference3.ReservationDto GetReservation(int ReservationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetReservation", ReplyAction="http://tempuri.org/IReservationService/GetReservationResponse")]
        System.Threading.Tasks.Task<ServiceReference3.ReservationDto> GetReservationAsync(int ReservationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IReservationServiceChannel : ServiceReference3.IReservationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ReservationServiceClient : System.ServiceModel.ClientBase<ServiceReference3.IReservationService>, ServiceReference3.IReservationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReservationServiceClient() : 
                base(ReservationServiceClient.GetDefaultBinding(), ReservationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IReservationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ReservationServiceClient.GetBindingForEndpoint(endpointConfiguration), ReservationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReservationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReservationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference3.ReservationDto[] GetReservations()
        {
            return base.Channel.GetReservations();
        }
        
        public System.Threading.Tasks.Task<ServiceReference3.ReservationDto[]> GetReservationsAsync()
        {
            return base.Channel.GetReservationsAsync();
        }
        
        public void DeleteReservation(int ReservationId)
        {
            base.Channel.DeleteReservation(ReservationId);
        }
        
        public System.Threading.Tasks.Task DeleteReservationAsync(int ReservationId)
        {
            return base.Channel.DeleteReservationAsync(ReservationId);
        }
        
        public void AddReservation(ServiceReference3.ReservationDto reservation)
        {
            base.Channel.AddReservation(reservation);
        }
        
        public System.Threading.Tasks.Task AddReservationAsync(ServiceReference3.ReservationDto reservation)
        {
            return base.Channel.AddReservationAsync(reservation);
        }
        
        public void UpdateReservation(ServiceReference3.ReservationDto reservation)
        {
            base.Channel.UpdateReservation(reservation);
        }
        
        public System.Threading.Tasks.Task UpdateReservationAsync(ServiceReference3.ReservationDto reservation)
        {
            return base.Channel.UpdateReservationAsync(reservation);
        }
        
        public ServiceReference3.ReservationDto GetReservation(int ReservationId)
        {
            return base.Channel.GetReservation(ReservationId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference3.ReservationDto> GetReservationAsync(int ReservationId)
        {
            return base.Channel.GetReservationAsync(ReservationId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReservationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReservationService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57387/ReservationService/ReservationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReservationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IReservationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReservationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IReservationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IReservationService,
        }
    }
}
